# Generated by Django 2.2.4 on 2019-09-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtests', '0002_auto_20190916_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserecord',
            name='execute_status',
            field=models.CharField(choices=[('P', 'Pending'), ('B', 'Block'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
