# Generated by Django 2.2.4 on 2019-09-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtests', '0004_auto_20190925_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserecord',
            name='bug_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
