# Generated by Django 2.2.4 on 2019-10-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtests', '0005_caserecord_bug_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='M', max_length=1),
        ),
    ]
