# Generated by Django 2.2.4 on 2019-11-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtests', '0006_auto_20191008_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text_field', models.TextField(default='')),
            ],
        ),
    ]
