# Generated by Django 2.2.4 on 2019-11-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtests', '0007_reporttemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttemplate',
            old_name='text_field',
            new_name='info',
        ),
    ]
