# Generated by Django 2.2.4 on 2019-11-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtests', '0008_auto_20191108_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportTemplate',
        ),
    ]
