# Generated by Django 2.2.4 on 2019-11-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xtests', '0011_reportrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrule',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='rule',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='xtests.ReportRule'),
            preserve_default=False,
        ),
    ]
